### ISSUE TITLE
Define Tutorial Bug

### ISSUE THREAD

**Issue by AishmanTaylor** [swarm-game/swarm#1089]
Unable to place flower or pickerel weed in the inventory of the base despite the robot showing that it has been deposited. 

Using the following four definitions the navigate the maze: 
def move4 : cmd unit = move; move; move; move end
def move16 : cmd unit = move4; move4; move4; move4 end
def moveup : cmd unit = turn north; move; move end
def move4 : cmd unit = turn south; move; move end

When navigating the maze using these I have used both a combination of the 'harvest', the 'grab' the ' t <- harvest', and the 't <- grab' command to grab the flower. Then use a combination of 'place "flower"', 'place "pickerel weed"', 'place t' to try and get it into the base. This registers as grabbing the flower and then placing it somewhere when using the build command to run a robot through the maze and back. The robot has nothing in its inventory after running the place command but nothing is placed into the inventory of the base.

**Comment by byorgey** [comment]
Thanks for the report!  The command to get it into the inventory of the base is `give base t` (if you stored its name in the variable `t`).  I thought the tutorial explained the `give` command previously but it seems I was wrong.  See #1086 .

**Comment by xsebek** [comment]
It may also be that the unmoving "base" robot suggests that it is a location instead of a robot. :thinking:

I can imagine a simplified model where placing entities in the base adds them to the inventory, but that is not how it currently works. :smile: 

Side note for scenario authors: A system robot could await (#687) changes to the base location and grab and give entities to the base.
