### ISSUE TITLE
"turn down" is unrecoverable without compass

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1105]
**Describe the bug**
`turn down` sets the direction vector to zero, and no other command using relative directions can restore it.  You have now become literally "disoriented"!  Setting an absolute direction by way of the `compass` allows one to recover.

This issue has probably existed for a long time.

**To Reproduce**
The Ice Cream Shop scenario entails a mobile `base` without a `compass`.

    scripts/play.sh --scenario Challenges/ice-cream.yaml

then

    turn down

Now the base can no longer move in any direction.  Somewhat appropriately, the base is now displayed as `X`.

**Expected behavior**

May want to either exclude `turn down` as a command, either entirely or if a compass is not equipped.

On the other hand, if we can find a use for `turn down`, getting "stuck" this way may make for an amusing scenario.  Say, playing ostrich?

**Comment by xsebek** [comment]
Not an issue, as you point out, you could use it to implement some algorithms where you let the robot unwind its recursive stack at the end.

Leaving it out makes less sense since you should not need a compass to look down. :slightly_smiling_face:

Since it's really easy to not use it and even Tab complete will not suggest it (N,E,S,W) I am going to close this.
We can certainly revisit `down` if/when we do multiple Z-levels. In the meantime, we can use it to play ostrich.

**Comment by kostmo** [comment]
I suppose this phenomenon is analogous to [2-D gimbal lock](https://en.wikipedia.org/wiki/Gimbal_lock#In_two_dimensions).

**Comment by kostmo** [comment]
Related (historical): #332
