### ISSUE TITLE
Consistently use "capability style" for all error handling

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1122]
> In general it would be nice to use e.g. a `Has (Throws SystemFailure) m` constraint rather than using an explicit `ExceptT`. I know we already have `ExceptT` in a few places, but a lot of our code is already in the "capability style" where we have a generic monad m and just say what constraints it must satisfy, and this kind of style is more flexible since you can use it at multiple concrete types, as opposed to using explicit monad transformers which limits you to use exactly that type.

From [this comment](https://github.com/swarm-game/swarm/pull/1116#discussion_r1111139757).

**Comment by xsebek** [comment]
@kostmo I inlined the comment so that it's easier to see what needs to be done. :wink: 

My preference would be to use these styles:
- pure functions:
    ```Haskell
    parseSomething :: Bool -> Text -> Either String Term
   ```
- monadic `fused-effects` style in the game code:
    ```Haskell
    execWhatever :: (Has (Throws Text) sig m) => Term -> m Bool
    ```
  - ideally, we would use this for everything to avoid code bloat of wrap/unwrap in already long game code
- a brick `EventM` monad (`MonadIO` and `MonadState`) in UI code
  - maybe we could make it a concrete fused effect carrier and then all code could be consistent? :thinking:
