### ISSUE TITLE
Publish Yaml.Environment as independent library

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1128]
We should publish the `Swarm.Util.Yaml` module as an independent library that other Haskellers might find useful.

I think it is a perfectly valid approach to depend on the environment when parsing YAML and it is not specific to Swarm.

## Solution

1. Create a separate repository `swarm-game/yaml-environment`.
2. Make it a simple library with the module `Data.Yaml.Environment`.
4. Publish to Hackage.
5. Import it in Swarm.
6. Profit!

## Considerations

We might want to make some changes before publishing:

- use standard `Reader` instead of `With`?
- rename `FromJSONE` to `FromJSON[With|Env|Environment|Reader]`?
- add a `ToJSONE` class that will be basically `ToJSON (Writer a)` to complement `FromJSONE`?

**Comment by byorgey** [comment]
I am sort of ambivalent about this.  On the one hand, I agree it is not really specific to Swarm and I suppose it might be useful to others.  On the other hand, it would be a bunch of work to split it out, clean it up, create documentation, etc. and then commit to keeping it updated separately.  Step 5 is obviously a joke, because the only people that *might* profit would be other Haskellers, not us. :smile: 

I am adamantly opposed to adding `ToJSONE` unless someone actually wants it; otherwise it sounds a lot like a solution without a problem.
