### ISSUE TITLE
Allow system robots to execute a large program in a single tick

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1227]
There should be a privileged variant of `atomic` that allows an arbitrarily large program to be executed in a single tick.
This would be useful for setting up a play area with randomness, for example in the word search challenge (#999).  As is, the player robot needs to be confined and to wait patiently while the system robot does a bunch of work.  Unless the system robot is programmed carefully, the solution might be revealed to an observant player as the playfield setup is performed.

**Comment by byorgey** [comment]
Ah, yes, that's a good idea, and it should be pretty easy.  We could just do away with the `validAtomic` check for system robots, although in practice that is a little tricky since the `validAtomic` check is done *statically*, during type checking, but we won't know what capabilities the robot executing it will have until runtime.   I guess we could just make a new `super_atomic` primitive (or whatever) that is just like `atomic` except that it requires `god` capability and does not do any validity checking.
