### ISSUE TITLE
Implement language server OnHover handler

### ISSUE THREAD

**Issue by TristanCacqueray** [swarm-game/swarm#124]
Once source locs are attached to the Type info, we can implement the hover handler to display the type of the current expression. Here is an example of such handler: [Dhall.LSP.Backend.Typing](https://github.com/dhall-lang/dhall-haskell/blob/1366883c2891d1bec411aef4616cfc7d177478a4/dhall-lsp-server/src/Dhall/LSP/Backend/Typing.hs#L32)

**Comment by byorgey** [comment]
So after staring at the Dhall code, I think what it is doing is this: given a term that has been annotated with source info, and a location (i.e. where the mouse is hovering), return a span corresponding to the thing the mouse is pointing at, along with a type for it.  I am not quite sure how they are getting the type... does it recompute the type from scratch?  Or is there some type information already cached/annotated in the term that it can use?

I guess recomputing the type from scratch would not actually be that bad. The typechecker is pretty fast (remember, we run the parser and typechecker from scratch every time the user types a single character!). We don't currently cache any type information inside terms, so that would definitely be the easier approach.

**Comment by TristanCacqueray** [comment]
If I remember correctly, dhall lsp recomputes the type from scratch.

**Comment by byorgey** [comment]
Makes sense.  I wonder if we could just generalize the typechecker a bit so that it takes an optional location.  So it can either return the type of an entire expression if you don't specify a location, or the type of just a particular subexpression if you do.  I hope we can figure out how to do it this way because I don't want to have to duplicate all the typechecking logic.

**Comment by xsebek** [comment]
@byorgey in Haskell I actually prefer the specific type when debugging (e.g. parsers), but HLS is kind enough to show me both. 🙂

**Comment by xsebek** [comment]
Btw. I think this would be a massive improvement when writing complicated programs. :+1: 

While writing the programs for the Hanoi challenge in #669 I often needed to know the type of specific functions. Even getting the type of basic commands would be useful, as I do not remember them all. :sweat_smile:

Also, we have documentation for all basic commands, that we currently only use for generating the Wiki, could those be shown in the OnHover as well? :slightly_smiling_face:
