### ISSUE TITLE
Create proper, static website for Swarm

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1446]
Right now we just point people at the github repo, which is fine, but eventually I think we will want a nice website with cool screenshots, download instructions, maybe a blog, *etc.*

A great initial option could be to use [Hakyll](https://jaspervdj.be/hakyll/) to build a static site and have it hosted via GitHub pages at `swarm-game.github.io`.  (Leaving open the possibility of registering `swarm-game.org` or something like that in the future.)

See also #1259 , which envisions a much more ambitious, dynamic website.

**Comment by xsebek** [comment]
It would be great if we could push artefacts from CI there - namely products of `swarm docgen` and Haddock. 🙂

**Comment by byorgey** [comment]
@ElderEphemera glad for you to work on this!  Let the rest of us know if there's any ways we can help.

**Comment by ElderEphemera** [comment]
> @ElderEphemera glad for you to work on this! Let the rest of us know if there's any ways we can help.

Thanks! I've been meaning to contribute more here for a while now.

I've started on a Hakyll site as suggested, keeping the setup as simple as possible for now. Here's what I have so far, with all the content just taken from the README:

![image](https://github.com/swarm-game/swarm/assets/2855417/cd6de192-3116-4ce7-89b7-55a6e9942bb3)

Let me know what you think visually. I was afraid that mimicking the game like this might hinder readability, but I think it turned out fine (unless I'm just too used to monospaced text).

With regards to a blog, did you intend for the posts in `docs/blog` to be mirrored on the site (I see they're already on https://byorgey.wordpress.com/)? If so should they be included in the repo as is, i.e. with the BlogLiterally metadata intact? I'm not sure what you're setup is there.

Also if someone in the org could create a `swarm-game/swarm-game.github.io` repo, and give me access, that would be great.

**Comment by byorgey** [comment]
Hah, I think mimicking the game visually looks cool.  It maybe looks a little crowded, like there's too much information crammed onto the page, but that will also get better as we refine what content is on the page.

> With regards to a blog, did you intend for the posts in docs/blog to be mirrored on the site

Sure, I don't see why not.  But you can delete the BlogLiterately metadata, that won't be relevant in this context.  I think my idea is that if we get a blog set up, we can just post announcements etc. there and I can stop posting them to my personal blog.  So ultimately new posts can be stored here instead of in `docs/blog`.

> Also if someone in the org could create a swarm-game/swarm-game.github.io repo, and give me access, that would be great.

Done, I think.  Let me know if it worked.

**Comment by ElderEphemera** [comment]
> Done, I think. Let me know if it worked.

Looks good to me, thanks.

I think I'll finish the blog part, then put up what I have and go from there if that's good with you.

**Comment by ElderEphemera** [comment]
The site is up at https://swarm-game.github.io/! Please let me know anything that needs to be changed.

**Comment by byorgey** [comment]
This is amazing!  Thanks @ElderEphemera !
