### ISSUE TITLE
`build` does not see correct requirements for `let`-bound variables

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1466]
The requirements analysis does not seem to correctly handle local variables.

Observe following two programs in creative scenario:
```
def y = log "hi" end;
let y = instant (a <- grab; place a) in build {y};
r <- robotNumbered 1; view r
```
```
def y = instant (a <- grab; place a) end;
let y = log "hi" in build {y}
r <- robotNumbered 2; view r
```

The order is simply swapped, but in each case, the built robot gets the wrong devices.

**Comment by xsebek** [comment]
@byorgey I don't fully understand current requirement analysis, but the process seems odd to me.

Instead of creating a map of requirements for globals, shouldn't the result be adding `requires` inside build?

https://github.com/swarm-game/swarm/blob/49903de26d101d1284adc1460aaeaea6fdb61e48/src/Swarm/Language/Requirement.hs#L226-L233

While recursing through the term, the context is correct, but once we leave it the locals will be lost.

**Comment by byorgey** [comment]
I agree it is a bit confusing but I think there's nothing wrong with that code you linked.  Requirements analysis is something of a mess. I think this issue is due to a combination of the following:
- Currently, we check requirements for arguments to `build` dynamically, at runtime (see below).  This is not really the right thing to do, but currently we don't have a type/requirements system which is rich enough to check arguments to `build` statically. (See #231 .)

  https://github.com/swarm-game/swarm/blob/61df42e7b9f6868b6b1b8c06c81874a4cd33d96e/src/Swarm/Game/Step.hs#L1831-L1836

- When we evaluate `let` expressions at runtime, we don't currently modify the requirements map at all.  This is clearly a bug but I think it might be annoying to fix.  Right at the moment when we start evaluating a `TLet` we need to do requirements analysis on the let-bound term (while it is still a `Term` and we can analyze it), then store the resulting requirements somewhere (perhaps by stuffing them in the `FLet` frame?) so that when we get around to evaluating the body of the `let`, we can locally update the requirements map appropriately.

**Comment by xsebek** [comment]
@byorgey just so I understand the evaluation/execution distinctions better, what would happen if we stuffed our findings to build **during elaboration**?

I linked the recursive walk through AST because it seems correct to me - the problem is that we collect results and apply them out of context. What if instead we applied the knowledge to build while we are in the AST and the context makes sense?

Let's say a god mode `buildWithKnownRequirements` command takes also all the requirements as a string (hack, but easy to imagine for me).

I think this is different from your `FLet` approach. 🤔

**Comment by byorgey** [comment]
> @byorgey just so I understand the evaluation/execution distinctions better, what would happen if we stuffed our findings to build **during elaboration**?

I mean, yes, that is exactly part of the idea behind #231 , and yes, it is different from my (flawed) `FLet` approach.  But to actually do it correctly requires modifying the type system to unify types and requirements.  I will have to give some thought to whether we can do this in a simple way as a stopgap for now.
