### ISSUE TITLE
`path` command should use relative coordinates and orientation

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1544]
Currently it accepts absolute coordinates and returns an absolute direction.  However, its use shouldn't presuppose a `GPS` or `compass`.

**Comment by byorgey** [comment]
Currently, since the `path` command is really only usable by system robots or robots in a designed scenario, I don't know that it matters all that much.  And even if we do eventually make a craftable device for it, I imagine it will be a fairly complex and high-level thing to craft, by which time it's entirely reasonable to suppose that the player can craft `GPS` and `compass` devices (in fact, we might consider having `GPS` and `compass` be part of the recipe!).

I think it would be annoying if the `path` command took relative coordinates as input, because in most cases when using the command I am probably going to be thinking in terms of absolute coordinates ("I want to go to location X, where thing Y is") so it would just require an annoying step of subtracting my robot's position to turn the absolute coordinates I have in mind into relative coordinates to give to `path`.

I am more sympathetic to the idea of `path` returning relative directions like `left` (though it will still have to sometimes return directions like `north`, *e.g.* if the robot's orientation is `down` or some other non-unit vector).  But I'm not sure I see much benefit besides not requiring the use of a `compass`.  In fact, it feels like getting absolute directions might actually be more useful, since I can more easily write conditions based on the result ("if the closest thing X lies to the `north` ...").

**Comment by kostmo** [comment]
Ok, I'm convinced to leave the behavior as is. Making `GPS` and `compass` be part of the recipe is a great idea.
