### ISSUE TITLE
Try `eff` effect library

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1559]
⚠️  _**Disclaimer:** This is absolutely a **huge undertaking**, but it might just be worth it. Get free experience working with effects._

---

Currently we are using the fused-effects library, which provides a nice API to work with state.

However, we read and update state a lot* so having more efficient effect library could make significant a runtime difference.

<sup>*) not sure what the exact number is, but browsing the profile it seems like most function in step spend most time in get/put/modify.</sup>

Let's try porting swarm to `eff` since fused-effects say this about it:

> [eff](https://github.com/lexi-lambda/eff) is similar in many ways to fused-effects, but is slightly more performant due to its representation of effects as typeclasses. This approach lets GHC generate better code in exchange for sacrificing the flexibility associated with effects represented as data types. `eff` also uses the monad-control package to lift effects between contexts rather than implementing an Algebra-style class itself.

**Comment by byorgey** [comment]
I am pretty strongly opposed to this, for a few reasons.  First, as you say, it would be a massive undertaking.  I expect porting to a different effects library would probably take... I don't know, 20 hours of work?  It would be truly massive, not only because you would have to touch so much code, but also because different effects libraries always have slightly different ways of doing things.  When I have done such conversions before it has always required some head-scratching to figure out how to refactor things to make use of the new library's peculiar features and ways of doing things.  And after doing all that work, how much of a performance benefit will we get... who knows?  I chose `fused-effects` because it is fast, but I know `eff` is built on top of some cool new runtime support from GHC to make it really fast.  But in any case I suspect there is lots of lower-hanging fruit in terms of optimization that we can tackle first.

Second, `eff` is still "under construction" and it is not even on Hackage.  So building and distributing Swarm would get much harder.  At ICFP I talked with several people working in this space, including Lexi (the author of `eff`) and Nick Wu (one of the authors of the paper on which `fused-effects` is based) and my sense is that we are getting close to having the "one true effects library" which is blazing fast and has all the nice features, but we're not there yet.  If we switch to `eff` we might just have to switch to something else again soon after.

After having said all this, of course, if someone really wants to put in the enormous amount of work needed to try porting to `eff`, I can't stop them, and I'm sure we would learn something interesting.  But because of reason (2) I would not be in favor of merging such a change.

**Comment by xsebek** [comment]
@byorgey Ah, I was not aware of the (2), that is a blocker. The changes are in merged GHC now though, so I am hopeful it will be released some day soon.

I expect the <kbd>C-Project</kbd> and ___Disclaimer___ will be enough to ward off all but the most brave souls. 😄 

By the time we pick all the low hanging fruits, maybe the one true library will be released. 🙂 I don't care much if we keep this open or not, though it would be really interesting to know how `eff` compares on medium size project like `swarm`.

**Comment by xsebek** [comment]
Actually given (2) and our lack of performance measurements it would be a waste of time, so let’s not even suggest such foolish ideas.

Thanks for the ingo @byorgey.

**Comment by byorgey** [comment]
@xsebek What is "ingo"?

**Comment by xsebek** [comment]
*info, yes
