### ISSUE TITLE
Unicode characters are escaped in pretty-printed `Text` values

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1943]
**Describe the bug**
The `format` command escapes the Unicode character `∀`.

**To Reproduce**
Type in REPL:
```
> tydef L a = rec l. a * 1 end
> format {(undefined) : L a}
it : Text = "{undefined : \8704 a. L a}"
```

**Expected behavior**
The `format` command should show the ASCII `forall` or Unicode `∀`.

**Additional context**
This could be related to escaped characters in strings, like `\n`.

Discovered while testing https://github.com/swarm-game/swarm/pull/1928#discussion_r1641906543.

**Comment by byorgey** [comment]
Aha, it turns out the problem is not `format`, the problem is how we pretty-print `Text` values:

https://github.com/swarm-game/swarm/blob/f607470113da8c13b3543e43bc3755ad3be44164/src/swarm-lang/Swarm/Language/Pretty.hs#L270

Currently we just call `show` on the underlying `Text` value, which automatically handles wrapping it in double quotes and turning things like newline characters into escape sequences.  But it also turns many non-ASCII characters into escape sequences as well (which is [controversial](https://gitlab.haskell.org/ghc/ghc/-/issues/20027)).  But in any case it looks like we can probably just use [ushow](https://hackage.haskell.org/package/unicode-show-0.1.1.1) instead.

**Comment by byorgey** [comment]
A simpler test case is just:
```
> "∀"
it0 : Text = "\8704"
```
