### ISSUE TITLE
Highlight only the problem in REPL

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1956]
**Is your feature request related to a problem? Please describe.**
> It's annoying when you are in the middle of typing something like
> ```Haskell
> build {myComplexFunction ... }
> ```
> and you need to fill in the ..., but you can't remember exactly what the type of myComplexFunction is, but Swarm is no help because the entire thing does not typecheck so it is just highlighted in red.

@byorgey in #1955

**Describe the solution you'd like**
I want the function `renderREPLPrompt` to split the text into invalid and valid parts and color them separately.
The solution is to also have error location in REPL model and to use `processParsedTerm` in `validateREPLForm`.

**Describe alternatives you've considered**
We could use other ascii art tricks, for example write `ˆˆˆ` on the line under.

A more complex solution to solving type checking problems is in #1955.

**Comment by byorgey** [comment]
I looked into this a bit.  We draw the REPL using the `renderEditor` function from `brick`, which is essentially given some `Text` and must turn it into a `Widget`.  Currently we just wrap the `Text` with `txt` and slap a color on it based on the `replValid` field.  

Instead, I think we could (1) store something more informative in the `replValid` field, e.g. something involving a `ContextualTypeErr` and/or `ParseErrorBundle` (if we use `readTerm'` instead of `readTerm` to parse), then (2) in `renderREPLPrompt`, slice up the given `Text` based on positions found in the error (if any) and color the pieces differently.

**Comment by xsebek** [comment]
@byorgey I have an MR ready in a bit, but you might outrace me 😆

**Comment by byorgey** [comment]
Hah, I wasn't working on writing any code, just thinking about how it might be done. :smile:
