### ISSUE TITLE
Use Generics or TH to get Enum/Bounded

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#2018]
**Is your feature request related to a problem? Please describe.**

GHC/Haskell Report does not support deriving `Enum` for nested data types.
This inhibits refactoring to group related constructors together, for example:
```diff
  data WorldEvent
    = ViewBaseEvent
    | ShowFpsEvent
-   | MoveViewNorthEvent
-   | MoveViewEastEvent
-   | MoveViewSouthEvent
-   | MoveViewWestEvent
+   | MoveViewDirectionEvent AbsoluteDir
```
**Describe the solution you'd like**

> I [asked about this on Discourse](https://discourse.haskell.org/t/enumerating-all-values-of-a-nested-sum-type/9907), and got some good suggestions:
> * [universeGeneric](https://hackage.haskell.org/package/universe-1.2.3/docs/Data-Universe.html#v:universeGeneric) from the universe package
> * the [finitary](https://hackage.haskell.org/package/finitary-2.1.2.0/docs/Data-Finitary.html) package

@kostmo in https://github.com/swarm-game/swarm/pull/1979#discussion_r1667463464

**Describe alternatives you've considered**

Handwriting the instances by hand is annoying and error-prone.
We could also use a list, which is less annoying, but very easy to get out-of-date.

**Additional context**

There are likely a few types in Swarm that either workaround a missing `Enum` instance or are huge to derive it:
* `WorldEvent` has handwritten instance
* `Const` has 107 unary constructors and is 251 lines long

**Comment by byorgey** [comment]
`finitary` looks cool but possibly overkill for what we need: it automatically computes the cardinality of a type (which shows up as a type-level `Nat` index) and allows converting between numeric indices and values of the type (like `toEnum` and `fromEnum`).  `universe` is a bit simpler but probably provides everything we need (namely, the ability to produce a list of all the inhabitants).  Both seem actively maintained so that's not an issue.
