### ISSUE TITLE
Fix Windows CI caching

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#2040]
**Describe the bug**

Windows build rebuilds dependencies and does not seem to be cached.

**To Reproduce**

Open a PR that changes Haskell file and check Windows CI build log.

**Expected behavior**

The dependencies should be cached from prior runs.

**Additional context**

See discussion in #2036.

**Comment by xsebek** [comment]
It did seem to work in #2034: https://github.com/swarm-game/swarm/actions/runs/9926216855/job/27419538109,

**Comment by byorgey** [comment]
No cache was found here: https://github.com/swarm-game/swarm/actions/runs/9944450117/job/27470533789?pr=1980

Since that PR did not change any Haskell files at all (only 3 markdown files and changed the version number in the `.cabal` files) I would have hoped that it would be able to reuse builds of many dependencies...
