### ISSUE TITLE
Ability to include one file of definitions in another

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#208]
**Describe the bug**
Using the command `run X` does not run file `X` before checking next expression.

**To Reproduce**
Consider files `x.sw` and `y.sw`:
```haskell
def x = 1 end;
```
```haskell
run "x";
def y = x + 1 end
```
Writing `run "y"` in REPL produces:
```
run: Error in test2
 2: Unbound variable x
```

**Expected behavior**
I would expect it successfully load both variables.

**Comment by byorgey** [comment]
Maybe the right thing to do here is to just bite the bullet and have special typechecking for the `run` command: typechecking `run` would actually load the file, typecheck it recursively, and then make available the types of any definitions to things after the `run`.  Some thoughts:

- We have to be careful that import cycles don't get the typechecker stuck in an infinite loop.
- Ideally, we would only load a file from disk once, instead of loading it once at typechecking time and once at runtime.
- We could solve both the above problems by maintaining a map from module names to parsed, typechecked, and elaborated terms.  
- All of the above would mean adding several new effects to the `Infer` monad (namely, `IO`, and some kind of state effect with the current map from file names to checked terms).

**Comment by byorgey** [comment]
I am now more convinced that the above comment is the right way to do things.  We might also consider renaming `run` to something like `import`.

**Comment by byorgey** [comment]
Closing this in favor of #495 .  Of course it will still be here for anyone who wants to read the discussion.
