### ISSUE TITLE
Bad application of execConst - `Fst [VInt 4]`

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#2186]
**Describe the bug**

While writing a benchmark for dictionaries/sets, I ran into a bug that caused Swarm to become unresponsive.
After trying to debug this and removing some code I got a runtime error instead:
```
Fatal error: Bad application of execConst:
Fst
[VInt 4]
```

<details>
  <summary>Click to see full exception</summary>
<img width="500" alt="Screenshot 2024-10-19 at 4 15 07 PM" src="https://github.com/user-attachments/assets/dcd166ca-a6d7-4de1-b56b-b27fa52ba8ff">
</details>

**To Reproduce**

Run the benchmark in d7ffc68:
```
run "example/recursive-containers.sw"
bench_insert 0
```

**Expected behavior**

I expect the benchmark not to cause Swarm to become unresponsive or report runtime type errors.

**Comment by byorgey** [comment]
I can reproduce this.  Looking into it now.

**Comment by byorgey** [comment]
@xsebek Can you tell me what type you expect `runM` (in the definition of `benchmark`) to have?  The first argument is `acc` which must be some kind of tuple, since we call `fst acc` and also return it as the result of `runM` which also must return a tuple.  However, the recursive call to `runM` is `runM (fst acc + t) ...` which seems to be passing an `Int` to `runM` instead of a tuple.  If we end up passing a number to a function expecting a tuple this is exactly what I would expect to happen at runtime; in that case the bug is somewhere in our typechecker.

**Comment by byorgey** [comment]
I've managed to whittle it down to the following much smaller example:
```
def bad : Int -> Cmd Int = \times.
  let runM = \acc.\n.
    if (n <= 0) {
      return acc
    } {
      runM (fst acc + 1) (n - 1)
    } in
  res <- runM (0, ()) times;
  return (fst res)
end
```
This typechecks and loads fine (though it should not!), then trying to evaluate `bad 1` yields a fatal error (as one would expect).  Intriguingly, if we remove the `+ 1` after `fst acc` then it no longer typechecks, but instead yields an infinite type error.

**Comment by xsebek** [comment]
Ah, I was using the result `(total, (minTime, maxTime))`, but I wanted to simplify it for debugging so I removed the tuple.

Once I removed the last parts it works. 😮 
<img width="355" alt="Screenshot 2024-10-19 at 5 19 35 PM" src="https://github.com/user-attachments/assets/88651b6c-f836-4a22-90f1-74a0cbc88abc">

**Comment by byorgey** [comment]
Aha, the problem was that for some boneheaded reason (probably an incomplete refactoring) we were directly calling `=:=` in the case for a recursive let binding where we needed to infer the type, and then discarding the result!  In other words, if the type inferred for the body did not unify with the variable generated for the type of the whole thing... it was just ignored. :facepalm:
