### ISSUE TITLE
Counter overflow

### ISSUE THREAD

**Issue by Nuxssss** [swarm-game/swarm#245]
When I hold the '>' button, the speed counter increases so that it reaches negative values, and then completely to zero.
[video](https://radikal.ru/video/7VY65tw1BSn)

**Comment by byorgey** [comment]
Thanks for the report!  I think what is happening here is that internally, we just store a counter which is the *log base 2* of the number of ticks per second, e.g. 3 means 8 ticks per second, 4 means 16 ticks per second, etc.  So when you keep holding `>` the counter keeps going up until 2 to the power of the counter overflows an `Int`.  (That's why you can then go back down with `<`, because the internal counter does not overflow, only the number being calculated to show on the display.)  I agree we should cap it at something, maybe just cap the `lgTPS` to be between -30 to +30.  Not that anyone's computer is going to be able to compute 2^30 ticks per second anyway.

> we do not actually go faster then 30ticks/1s

No, we don't go faster than 30 ticks per *frame*, and there can be any number of frames per second depending on how fast your computer can render them.
