### ISSUE TITLE
Self-destructing `base` should be impossible

### ISSUE THREAD

**Issue by noahyor** [swarm-game/swarm#297]
I was playing creative mode and I 'selfdestructed' myself (the base) and I am wondering whether this should be possible in creative mode.

**Comment by xsebek** [comment]
If you are asking "whether it is still posible in the latest version" then sure, it is:

![Screenshot of selfdestruct](https://user-images.githubusercontent.com/44544735/151663833-2cb23607-db50-42a1-b343-124e7f59f619.png)

You can still scroll the map and <kbd>Ctrl</kbd>+<kbd>Q</kbd> to quit, but otherwise there is not much left to do :smile:

**Comment by byorgey** [comment]
But perhaps it shouldn't be possible... it seems like it is too easy to do accidentally, if you e.g. define a function that self-destructs at the end but then accidentally run it on base instead of as an argument to `build`.

**Comment by xsebek** [comment]
Yes, I was a bit surprised by the question too :smile: If we had quick-save it would not be a problem, but losing all the definitions and robots by `selfdestruct` could be a little harsh.

Then again it should not even be mentioned anywhere in the tutorial now? If only developers know about it, then it should not be _that_ dangerous :sweat_smile:

**Comment by byorgey** [comment]
How about adding a way to "resurrect" the `base` if it gets destroyed in creative mode?  Like if you're in creative mode, and the game notices that there is no `base` robot any more, it could print an appropriate message in the REPL window, and enable a key that would resurrect the `base`.  

> Then again it should not even be mentioned anywhere in the tutorial now? If only developers know about it, then it should not be _that_ dangerous sweat_smile

I think `selfdestruct` is still used in some of the examples in the `example` directory, which may have been what @noahyor was looking at.

**Comment by Alexander-Block** [comment]
> How about adding a way to "resurrect" the `base` if it gets destroyed in creative mode? 

That would probably solve this problem, but I am wondering: is there ever a reason to allow `base` to be destroyed? Because `base` is linked to the evaluation/execution of code entered into the REPL and loaded from files, destroying `base` would always make it necessary to resurrect it in order to continue playing. So wouldn't it be simpler to skip this step and just make it impossible to destroy `base` even in creative mode?

Trying to `selfdestruct` or `move` the robot `base` into water without a float capability could be handled analogously to trying to `move` through an unwalkable entity or to `grab` an entity that is not portable by throwing a `CmdFailed` exception instead of executing the command.

**Comment by byorgey** [comment]
Yeah, I think I agree with you @Alexander-Block .  We could even throw an exception with a funny message like "You consider destroying your base, but decide not to do it after all."
