### ISSUE TITLE
fatal error: Reference to unknown memory cell

### ISSUE THREAD

**Issue by noahyor** [swarm-game/swarm#299]
I was playing around with `salvage` in creative, and because of a (somewhat) fatal error in one of my programs, I had 1,112 robots in the `(0, 0)` location. I moved over there and defined `salvageALot` as `: Int -> Cmd () = \n. repeat n salvage`. I then ran `salvageALot 1112`, but it did nothing. Can you please help me with this?

**Comment by noahyor** [comment]
The error I got was `[Base] fatal error: Reference to unknown memory cell 10`.

**Comment by xsebek** [comment]
It would be great if you could include a reproducible steps to get this error, I experienced it a few times, but that should have been fixed. :slightly_smiling_face: 

What helped me, was to redefine all the necessary definitions again. That is, scroll to `def repeat`, hit <kbd>Enter</kbd> and repeat (no pun intended) for `salvageALot`.

@byorgey will know more, but I assume that "memory cell 10" is the `repeat` (or its part) and somehow it was lost in the meantime?

**Comment by xsebek** [comment]
@noahyor I found what the issue I encountered was: https://github.com/byorgey/swarm/pull/223#discussion_r735108493

Do you remember if you cancelled your `repeat` computation?

**Comment by noahyor** [comment]
I don't think I canceled `repeat` at any point, but I talked to @byorgey about it and he says that he has an idea of what is happening.

**Comment by noahyor** [comment]
I don't think I canceled the computation of `repeat`, and I tested `salvageALot 1`, but it still didn't work.

**Comment by byorgey** [comment]
I changed the title since I think `salvage` is a red herring.  I agree that memory cell 10 was probably storing the definition of `repeat` but got lost somehow.  Keeping the store in sync with the environment is tricky, but I thought we had it all worked out ... but apparently we don't.  I'm hopeful that knowing this is possible will give us motivation to figure out how to reproduce it.  Something about loading a definition of `repeat` via `run`, then using it in a definition... perhaps along the way re-loading the file, etc?

**Comment by noahyor** [comment]
I tried reloading example/BFS-clear.sw and `salvageALot` still did not work

**Comment by byorgey** [comment]
Yeah, I wouldn't expect reloading `example/BFS-clear.sw` to help, because the definition of `salvageALot` will still be referring to the version of `repeat` that was defined at the time `salvageALot` was defined.  The question is how we got into a state where the definition of `repeat` was referring to a memory cell that ended up getting trashed.

**Comment by byorgey** [comment]
So I am able to reliably reproduce this as follows:

- `m.sw` has contents
    ```
    def m : cmd () = move end
    ``` 

- Start a new game and switch to creative mode
- Now run the following commands:
    ```
    run("m")
    def x = m end
    run("m")
    r <- build {log "hi"; x}; view r
    ```

This yields a `fatal error: Reference to unknown memory cell 1`.

The basic issue seems to happen when we define a command at the REPL in terms of a command loaded from a file, and then reload the file.  The command should still work and should use the previous definition from the file.

**Comment by byorgey** [comment]
https://github.com/swarm-game/swarm/blob/d4aed9199799fd6735e8368d996a63a073fc11d6/src/Swarm/Game/Step.hs#L1277-L1289

Is it safe to use `emptyStore` in the last line, `Just t -> initMachine' t empty emptyStore k`?  I am not sure yet.
