### ISSUE TITLE
Switch entity tiles to use *mutable* arrays

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#30]
Right now we store the world as a triple: a collection of immutable terrain tiles, a collection of immutable entity tiles, and a map specifying which cells have been updated from their original entity values.  However, there is no good reason that we can't just use *mutable* arrays for entity tiles.  Running the game already takes place in a monad; we just have to make sure that it supports the mutable array operations.  This should hopefully make the implementation simpler and speed up the game as well.

**Comment by twitu** [comment]
I was looking into this and I can use a boxed mutable array like [`STArray`](https://hackage.haskell.org/package/array-0.5.4.0/docs/Data-Array-ST.html#g:1) could work here. The other options namely - `IOArray` and `StorableArray` do not really appear to fit this use case.

I'll also look into benchmarking the performance difference from making this change.

**Comment by twitu** [comment]
I agree with @polux's comments above that mutable arrays will certainly push a lot of interesting ideas out. Since the main reason for mutable arrays for performance I thought of trying out the changes to at least benchmark the performance difference.

I've take a stab at it in #278 using IO arrays and my conclusion is that IO is truly messy and it leaks everywhere. Currently the branch is not building because I've stopped at a couple of major roadblocks.

The changes to the World module itself are relatively small. It's just that the logic becomes much more imperative. However the main challenges that occur because of this are -

* The whole of `loadRegion` becomes IO because it involves loading the entity array. So by usage `loadRegion` -> `loadCell` -> `lookupEntity` and `lookupTerrain` also become IO. This still contained with World module so it's fine.
* This however affects View module very much. View is generated by "looking up" all the tiles and entities in a world, so everything gets polluted with IO. Not only does it make the some of the nested structures very difficult to write. But it also uses a monad for Context and so to deal with the two monadic contexts now needs effects where there was none.
* A few other pure functions like `changeWorld'` also need to be changed in Step module. The top level functions probably don't need change since it is already using the IO effect.

Overall even as an experiment using IO Array has turned out to be very hairy and is still not building. I might have better luck with ST Array. I'm open to suggestions if there's a better way to implement it.

**Comment by byorgey** [comment]
I'm going to close this --- I think we're all agreed that adding mutable state is not a great direction to go in.  Definitely still open to experimenting with other ways to get better performance, e.g. the suggestion to try `IntMap` for coordinates.
