### ISSUE TITLE
Prevent base from being able to move too early

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#334]
See the discussion at #92 .  Right now, the base can install anything it wants on itself, including treads, which let it drive around.

**Comment by xsebek** [comment]
In #373 I am about to add a new stronger motor for a `metal drill`, so maybe we could use it to power the base moving around?

Maybe we could add a "heavy" property to the base robot, which would be checked on moving.

A possible alternative would be to limit the base to one square with life support, which would lead to a different playthrough more centred on programming robots.

Generally, I would like to make this configurable so that we could experiment with scenarios and then choose whichever approach works best as default.

**Comment by byorgey** [comment]
It doesn't make sense to me that a certain *square* would have "life support" that you could drive away from.  Wouldn't the life support systems be built into the base itself?  Also I simply don't like the idea of *preventing* the player from doing things.  Making them difficult, sure, but making them arbitrarily impossible doesn't seem like good design to me.

I really do like the idea of having to construct some special "tank treads" or "heavy treads" using a stronger motor, some iron plates, etc. in order to move robots with a certain "heavy" property.

As an aside, I also had the idea of putting some harvestable entities around the world called `LaTeX`, represented by a `$` character, that you can use to make `rubber`, which would also be required for making treads (regular or heavy). =)  This has nothing in particular to do with the base moving around but just thought I would mention it.
