### ISSUE TITLE
Starting base with a large but finite supply of basic robot parts

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#35]
Right now, the base can build infinitely many robots with basic devices: a detonator, grabber, solar panel, and treads.  However, it is a bit unrealistic that we can make infinitely many of these.  Well, not that the game is realistic, but you know what I mean.  It might be worth considering instead:

* Do not any longer install those devices on robots by default; they must be available in the inventory just like any other device.
* Start the base out with a large number (100? 500? 1000?  maybe the number depends on the difficulty level? maybe different numbers of different devices, e.g. fewer detonators than treads?) of these devices, so that at the start of the game the user can construct a bunch of basic robots "for free", but will eventually have to think about producing more of these devices.
* In order to make this work, we also have to come up with recipes for these devices, and think carefully about how to balance the depth and difficulty.

**Comment by byorgey** [comment]
Maybe there should even be an entity for "robot chassis" with its own recipe, and building a robot requires one of those along with whatever devices it needs.

**Comment by abyo** [comment]
- I'll agree that having to install those devices manually would allow for more customization. If we assume that #49 add fog of war, we can use a robot for exploration only (no need for a `grabber`)? Besides, assuming #22 allowing us to have full control on the robot, we don't necessarily need a `detonator` since we can re-use it for multiple collecting tasks.
- When it comes to the number of robots/devices by default, if we can re-use the robot for multiple tasks (`program` command?), I'd suggest having no more than 50 (more or less depending on difficulty) robots and fewer `grabber` devices maybe?
- I suggested a recipe in #93 but not making too easy to produce would be great in my opinion.

**Comment by byorgey** [comment]
This becomes especially important if we restrict the use of the `view` command until later, as in #17 .  Then there would be no way to see and read about all the devices that get installed on robots by default.  If they were simply in the base's inventory to start then you could read about them before installing them on some robots.

**Comment by byorgey** [comment]
I think we should first generalize challenges to be a way to describe the starting conditions for any game (see #296) --- then we don't have to have magic numbers built into the code to say what the base's starting inventory should be; we would just have a file describing classic mode, including the base's starting inventory.  Or even multiple files with different levels of difficulty.

**Comment by TristanCacqueray** [comment]
A related confusing thing is that default devices installed on build can be salvage infinitely. In particular, it's a bit odd that the base does not have `treads`, but they can easily be acquired by salvaging a nearby robot early on. To avoid that, could we change the `salvage` output to filter out the default devices?

**Comment by byorgey** [comment]
I agree.  That will be fixed once we merge #361 since there will be no such thing as "default devices" any more.
