### ISSUE TITLE
Don't show memory references in pretty-printed values

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#350]
Currently, we store sub-results as "memory cells" printed as `@1`. Ideally, players would never see them and there would always be a way to print a value so that it could be reconstructed.

Consider for example simple `let`, which is printed fine:
```
> let f = \i.i in f
\i. i : ∀ a2. a2 -> a2
```
But recursive let is printed with the memory cell:
```
> let fix = \f. f (fix f) in fix
let fix = @33 in \f. f (force fix f) : ∀ a6. (a6 -> a6) -> a6
```
Similarly using other definitions uses memory cells:
```
> def f = 1 end
> let g = \_.f in g
let f = @51 in \_. force f : ∀ a2. a2 -> int
```
We could keep the original definitions and their dependencies and print those so that after overwriting `f` we could still print `g`:
```
// PROPOSED BEHAVIOUR BELOW
> def f = 1 end
> def g = \_.f end
> g
\_.f : ∀ a0. a0 -> int
> def f = 2 end
> g
def f = 1 end
\_.f : ∀ a0. a0 -> int
```

- keeping the original definition would help with #7

**Comment by xsebek** [comment]
Hey @byorgey, do you think this would be possible generally or at least in common cases?

Maybe we could keep the `Term` and `Env` in `VRef` from `VDelay`?

**Comment by byorgey** [comment]
So some of this is due to the way closures get printed.  When we evaluate a `TLam` we generate a `VClo` (a closure containing the bound variable, the lambda body, and the environment).  In order to pretty-print a value, we first convert it back into a `Term` using the `valueToTerm` function, which turns `VClo` into a `TLet` that represents the environment.  However, in these specific examples, the `let` is unnecessary, because the let-bound thing is actually already in the ambient environment.  I wonder if we could pass the existing top-level `Env` to `valueToTerm`, and have it omit `let`-binding things that are already in the top-level environment (with the same value!) as in the closure environment, when converting a `VClo`.

This would not eliminate memory references from ever showing up in pretty-printed terms (I think that is a tricky problem in general), but it would solve the examples you give here.

**Comment by byorgey** [comment]
So in order to solve #7 I think we are definitely going to have to save definitions somewhere.  So every time a `def` is executed (and maybe for `let` as well?), it will save both the source code of the definition as well as its value.  The thing I am still unsure about is how best to use this information for pretty-printing.  Maybe it's good enough to (1) try pretty-printing the *value* of each binding, but (2) if something is bound to a `VRef`, then pretty-print its definition instead.

**Comment by byorgey** [comment]
#1949 pretty much solved this.  The given examples no longer generate memory references:
```
> let fix = \f. f (fix f) in fix
it0 : ∀ a. (a -> a) -> a = \f. f (fix f)
> def f = 1 end
> let g = \_.f in g
it1 : ∀ a. a -> Int = let f = 1 in \_. f
```
The only thing that could still be improved is what I discussed in a [comment above](https://github.com/swarm-game/swarm/issues/350#issuecomment-1207500122): in the second example above, `g` does not need to be printed as `let f = 1 in \_. f`, it could just be printed as `\_. f` since `f` is in the ambient context.  I'm going to close this and split that out into a separate issue.
