### ISSUE TITLE
Add `knows` command

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#409]
## Problem
When we get to the tutorial testing `scan` and `upload`, we will need to check that the base has obtained the knowledge.

## Alternatives

Make existing command (`has` or `count`) return an optional value.

**Comment by xsebek** [comment]
How about if we threw an error on an unknown entity in `count` or `has`? Either one or both would be enough and would make this feature available to players when they obtain those commands.

**Comment by byorgey** [comment]
If one of them is going to throw an error, I think it would have to be `count`, since `has` is supposed to be easier to use earlier in the game.  Also, it just seems strange: if you don't know what X is, why should it be an error to ask whether you have any? The answer is obviously "no".  By the same argument I think it would be strange for `count` to throw an error.  I think it would also be annoying.  Imagine a scenario where some robots know about X, and now you want to build a new robot that has some if statement asking about how many X's it has (e.g. maybe another robot is going to give it some trees, and it should do something once it has 10 trees).  It would be super annoying if you have to remember to give it a tree first, or `upload` to it, just so that it doesn't crash the first time it asks how many trees it has.

**Comment by TristanCacqueray** [comment]
I have no opinion about this, but if `knows` is the way to go, then please find an implementation in #433 :)
