### ISSUE TITLE
Reconsider `StrictData`

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#415]
I do not think we are actually using the [`StrictData` default extension](https://gitlab.haskell.org/ghc/ghc/-/wikis/strict-pragma) that much.

Looking at the benchmark comparison between having it on by default ("strict") and not ("lazy"), I do not see a meaningful difference:

![comparison](https://user-images.githubusercontent.com/44544735/174280001-3c459455-9845-44d6-8867-83f4f440adde.svg)

Technically it's a percentual difference only for the shortest examples and for some `circlers` it is worse:

Benchmark | lazy | strict
-- | -- | --
run 1000 game ticks/idlers/10 | 2.13e-3 | -7.8%
run 1000 game ticks/idlers/20 | 2.15e-3 | -6.6%
run 1000 game ticks/idlers/30 | 2.21e-3 | -7.4%
run 1000 game ticks/idlers/40 | 2.22e-3 | -8.2%
run 1000 game ticks/trees/10 | 2.14e-3 | -9.0%
run 1000 game ticks/trees/20 | 2.18e-3 | -8.7%
run 1000 game ticks/trees/30 | 2.21e-3 | -8.1%
run 1000 game ticks/trees/40 | 2.24e-3 | -9.6%
run 1000 game ticks/circlers/10 | 0.18 | 1.1%
run 1000 game ticks/circlers/20 | 0.37 | 1.4%
run 1000 game ticks/circlers/30 | 0.56 | 0.3%
run 1000 game ticks/circlers/40 | 0.74 | 3.1%
run 1000 game ticks/movers/10 | 0.36 | -0.8%
run 1000 game ticks/movers/20 | 0.75 | 3.2e-2%
run 1000 game ticks/movers/30 | 1.15 | 0.4%
run 1000 game ticks/movers/40 | 1.55 | -0.3%
GeoMean (calculated) | 1.00 | -3.9%

Thanks a lot to [criterion-compare](https://github.com/bgamari/criterion-compare) for the nice output. :+1:

**Comment by TristanCacqueray** [comment]
Is there a case where using `StrictData` becomes an issue?

**Comment by xsebek** [comment]
@TristanCacqueray I do not think it makes any difference, so why *should* we have it on by default in every module? If I don't see a bang pattern or Strict pragma, I do not expect anything to be strict.

I would love some free performance, but I guess we would get more by using strict containers (or maybe not).

**Comment by byorgey** [comment]
When/why was `StrictData` added in thr first place?  I honestly don't remember.

**Comment by xsebek** [comment]
@byorgey good question, looking at blame, there was a commit ["fix up a few issues identified by stan"](https://github.com/swarm-game/swarm/commit/c86864b9871a820f7a63c3bea8203e500a5279e1).

I will have to see what [`stan`](https://github.com/kowainik/stan) says, maybe there is a good reason for this. :slightly_smiling_face:

**Comment by byorgey** [comment]
https://kowainik.github.io/projects/stan/report#STAN-0206

**Comment by xsebek** [comment]
Neither do I but I trust them to know better. :+1: 

I am still pondering putting it in the modules explicitly - if we ever stumble on a space leak, this will be easier to see and narrow down the search. I am not sure how much noise it would add though.

(By the way, `stan` is cool and has some 40+ nitpicks about the code :laughing: )

**Comment by byorgey** [comment]
> I am still pondering putting it in the modules explicitly

Yeah, I'm fine either way. 

> (By the way, `stan` is cool and has some 40+ nitpicks about the code :laughing: )

Yeah, I think I was playing with it for a bit back then, I haven't touched it since.  But you'll notice we still have a `.stan.toml` checked in.  I don't know if it would be worth adding it to our CI.

**Comment by byorgey** [comment]
I was thinking about this again recently when working on #468 , in which case we were building up a huge stack of `FUnionEnv` frames, each containing an environment.  In my fix #473 , we `union` the environments instead.  If the `FUnionEnv` constructor had lazy fields, then all this would accomplish is building up a huge unevaluated thunk with a chain of `union` calls instead of a stack of `FUnionEnv` frames.  But with `StrictData` the environments are actually unioned strictly. (At least, I'm 95% sure this is so: they are represented using `Data.Map`, and `union` on `Data.Map` is strict in the spine.  Relatedly but separately, perhaps we should be using `Data.Map.Strict` so that it is strict in the values as well.)

So again, `StrictData` is not about improving performance in general, but about possibly preventing some disastrous space leaks (which could affect performance).  I think I am in favor of leaving it as a default extension.

**Comment by xsebek** [comment]
Yeah, I am happy with knowing what it's useful for. Let's keep it and if we ever run into trouble we can revisit this.
