### ISSUE TITLE
Pass on mouse clicks to the REPL form

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#470]
When the user clicks on text typed at the REPL prompt, it would be nice if it caused the cursor to jump to the place where they clicked.  I don't think this should be hard; brick forms apparently already support mouse events, so all we need to do is notice and pass along the mouse events appropriately.

**Comment by lsmor** [comment]
I am trying to figure this out. I doesn't look that easy. The main problem is that I am completely overriding the behaviour of the cursor. I think, in order to make a simpler implementation we need to use the underliying [TextZipper](https://hackage.haskell.org/package/text-zipper-0.11/docs/Data-Text-Zipper.html#t:TextZipper) structure. The naive implementation of keeping the cursor in the uiState doesn't seem to be the right way.

**Comment by byorgey** [comment]
Yeah, keeping track of the cursor position ourselves is definitely not got to work. If we go down the route of keeping our own TextZipper it means we would have to completely reimplement everything the brick form is doing, which sounds terrible (and not worth it).

The idea would be to modify the code in `handleMainEvent` that handles a MouseUp event.  Currently, if the click is on the REPLpanel we simply set the focus to it.  But the idea would be to pass along the event to `handleFormEvent`.  We might have to add a `clickable` modifier to the REPL form itself, I am not quite certain how that part works. @TristanCacqueray might have more ideas.

**Comment by TristanCacqueray** [comment]
I had a look at supporting copy paste (through <kbd>ctrl</kbd><kbd>k</kbd> and <kbd>ctrl</kbd><kbd>y</kbd>), and I was not able to retrieve the cursor position from the brick Editor. It seems like we can only applyEdit.

Thus I guess it would be easier to handle mouse event directly in brick, and pass the event from swarm.

**Comment by jtdaugherty** [comment]
> I was not able to retrieve the cursor position from the brick Editor

FYI, it is possible with [editContentsL](https://hackage.haskell.org/package/brick-0.71.1/docs/Brick-Widgets-Edit.html#v:editContentsL) and [cursorPosition](https://hackage.haskell.org/package/text-zipper-0.11/docs/Data-Text-Zipper.html#v:cursorPosition), e.g.,

```haskell
import Data.Text.Zipper (cursorPosition)
import Brick.Widgets.Edit (editContentsL)
let (cursorRow, cursorCol) = cursorPosition $ someEditor^.editContentsL
```

**Comment by TristanCacqueray** [comment]
@jtdaugherty thanks you, I totally missed that :) I guess we can also use that lense to move the cursor for handling mouse clicks events? And/or do you think we could do this directly in the brick library?

**Comment by lsmor** [comment]
Well, I should try this out. As far as I remember, the problem is that we use a `Form` to represent the repl not and `Editor`, hence the solution would be a little more convoluted than simply use `Editor`'s lenses. I don't know how `Form`s and `Editor`s are related...

**Comment by jtdaugherty** [comment]
@TristanCacqueray looking at the code again, I'm going to think about updating editors to directly handle mouse clicks (just to change the cursor position). I didn't do that initially because it would require changing the editor's event handler function type to take `BrickEvent`s instead of `Event`s, and that's a breaking change. (But I think it would be worth it.)

@lsmor A `Form` works by dispatching events to an `Editor` contained in that form, including mouse clicks. That means that if I updated `Editor` to change its cursor on mouse click, any `Editor` in a `Form` would automatically behave accordingly without you needing to do anything.

**Comment by jtdaugherty** [comment]
@lsmor @TristanCacqueray I just released Brick 0.72 which adds mouse event handling to editors. Give it a try! There is a small API change that should be easy to incorporate (see the changelog).

**Comment by jtdaugherty** [comment]
(And 0.73 which includes @TristanCacqueray's `getCursorPosition` patch.)

**Comment by jtdaugherty** [comment]
Also, a note on the mouse event handling for editors: it may be obvious, but if not, that will only work if you forward mouse events to the editor (or `Form`). So if your top-level event handler is pattern-matching on e.g. `MouseDown` and handling it already, you'll need to forward that event to your editor (or `Form`) to get the benefit.

**Comment by lsmor** [comment]
@jtdaugherty thanks for the information!!!. Actually we are not passing mouse events to the editor I think, because it is used to select which panel is selected, but the event isn't forwarded. This is the very first change we need to do... :sweat_smile:

**Comment by byorgey** [comment]
Yeah,  @lsmor , passing along the event is what I was talking about in https://github.com/swarm-game/swarm/issues/470#issuecomment-1166335738 .
