### ISSUE TITLE
Add a flash memory recipe

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#498]
Add a recipe for flash memory that is the necessary device to `reprogram` a robot.

I want to have this capability comparably early, so how about:
- `circuit` + 8x`bit (0)` + 8x`bit (1)`

**Comment by byorgey** [comment]
What do you mean by "comparably early"?  A `circuit` requires `silicon`, which you have to make from `quartz` + a `big furnace` (which needs 10 `solar panel`s).  So that doesn't feel all that early to me, but then again, I'm not sure what you have in mind.  Personally, so far in my own strategy I tend to just use `salvage` a lot and I never use `reprogram`, so I have no particular opinion on how easy or difficult the `flash memory` recipe should be.

A `circuit` itself already requires 8 of each bit (though perhaps we should change that?), so it feels weird to combine a `circuit` with yet more bits.

**Comment by xsebek** [comment]
I think that reprogram should be available before plasma cutter and 3D printer.

That is, it should be easier to send robots to reprogram then to salvage&build new robot.

Maybe flash memory could just be bits? Then we could use it as an ingredient for circuit.

**Comment by byorgey** [comment]
Maybe flash memory = 8 bits of each type (currently the recipe for a counter), then counter = flash memory + 8 wooden gears?
