### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by kajvan** [swarm-game/swarm#53]
i am trying to use the command stack run but i get the error:

```
In the dependencies for brick-0.64:
    unix needed, but the stack configuration has no specified version  (latest matching version is 2.7.2.2)
needed due to swarm-0.1.0.0 -> brick-0.64

In the dependencies for vty-5.33:
    unix needed, but the stack configuration has no specified version  (latest matching version is 2.7.2.2)
needed due to swarm-0.1.0.0 -> vty-5.33
```

how can i fix this

**Comment by byorgey** [comment]
Ah, my apologies.  Swarm depends on `brick`, which depends on `vty`, and `vty` is not supported on Windows.  So that means Swarm only works on Linux or OSX, at least for now.  I would have mentioned it in the README if I had realized it.

I do not know whether it might be possible to get it to build on Windows using something like Cygwin or the Windows Subsystem for Linux. I would be happy to receive any reports either way.

I will leave this issue open and change the name as a place to collect ideas and information re: supporting Windows.

**Comment by abyo** [comment]
It is possible to get the game running with Windows Subsystem. Installation is really easy too those days.

```
wsl --install
```

Follow instructions (this will install ubuntu by default) then upgrade/update. Install ghc/ghcup.

```
sudo apt-get install ghc
curl -sSL https://get.haskellstack.org/ | sh
```

Install stack (if you didn't press yes before), cd in repo then stack.

```
ghcup install stack
stack run
```

**Comment by byorgey** [comment]
@abyo Thanks, glad it works!  I am curious, do you really need to `apt-get install ghc` first?  You should just be able to get `ghcup` then use that to install `stack`.

**Comment by abyo** [comment]
@byorgey I had an issue and found that installing ghc first resolved it, but I suppose you don't have too.

**Comment by amalloy** [comment]
I ran it on WSL as well. ghcup worked fine, after I installed the prerequisite packages it asked me for.

**Comment by byorgey** [comment]
Since it seems we have a viable path to building on Windows, I'm going to close this issue.
