### ISSUE TITLE
Implement run command for the web service 

### ISSUE THREAD

**Issue by TristanCacqueray** [swarm-game/swarm#625]
**Is your feature request related to a problem? Please describe.**
When playing with a text editor, it is not convenient to use the REPL to load new definitions.

**Describe the solution you'd like**
I would like to load swarm code using the web service directly from my text editor.
The editor integration could provide a `send-buffer` or something equivalent to automate that process.

**Comment by xsebek** [comment]
That sounds cool! Should this only accept definitions or also scripts?

I can imagine wanting to restart the scenario when writing a script to solve a maze, but only loading new definitions when playing the long game. :thinking:

**Comment by byorgey** [comment]
In swarm-lang there is no difference between definitions and scripts; a sequence of definitions *is* a script.  I don't think there's any reasonable way to restrict something to only accept definitions.

**Comment by xsebek** [comment]
@byorgey I was thinking that we could easily restrict that if you for example wanted to reload as you type, but not run any commands.

But that might not be a problem or could be offered as a config option later.

**Comment by xsebek** [comment]
@TristanCacqueray how would this work on the application state though?

The current Web API only has access to GameState, would this be a `Post '[Text] ()` type of endpoint where the text is parsed as `Term` and run by the base robot?

The alternative I see is adding some generic channel to the Web service, through which it would pass a `Term` and receive the `Value` once that term has finished executing. In the current brick application, we could route this through an event, so that it can be added to the `UIState` REPL history. But in principle, we could cut the brick part and run Swarm on a server, with the run term being executed in the base robot directly.

Honestly, I am really intimidated by the Servant types, so if you could add at least a minimal scaffolding for one POST method with error handling, that would make it much easier. 😉

**Comment by TristanCacqueray** [comment]
@xsebek I don't know how exactly how the text term would be submitted to the game state, but from the API perspective, the handler would look like this:

```haskell
type SwarmAPI =
  ... 
  :<|> "run" :> ReqBody '[JSON] Text :> Post '[JSON] Text

runHandler userSuppliedCommand = do
  term <- parse userSuppliedCommand
  eval term
  pure "completed"
```

- `ReqBody '[JSON] Text` indicates that the request will have a body of type `application/json` containing a text.
- `Post '[JSON] Text` indicate the path returns a text encoded in json.

The user would use the handler with `curl -XPOST -d'"the program"' -H 'Content-Type: application/json' localhost/run`
