### ISSUE TITLE
Add notification when game is not up-to-date

### ISSUE THREAD

**Issue by abyo** [swarm-game/swarm#66]
Right now whenever the game is having an update, we have no notification of it and that can create problems for people following the tutorial. I ran the game right after I saw the blog post and didn't tried it until next day. After reading the tutorial I got an error while typing this line.

```
build "fetch" {turn west; m8; thing <- grab; turn back; m8; give "base" thing; selfdestruct}
```

![](https://cdn.discordapp.com/attachments/871732319449395240/891253192644526111/update_error.png)

This happened because my game wasn't up-to-date and in this case it was because of the give command modification (23f69a1). After updating I could type the command just fine.

![](https://cdn.discordapp.com/attachments/871732319449395240/891253194817167360/update_solve.png)

It still took me a few minutes to understand that the error wasn't on my side. So I'm suggesting to implement a text that would tell the user to update his game. **Note that this problem isn't going to happen whenever we get in-game tutorial (#25) but it might still be relevant in the future to notify the user of new updates.**

**Comment by byorgey** [comment]
Ah, great idea!  I'm thinking something like:
1. Use https://hackage.haskell.org/package/githash to automatically compile in the hash of the latest git commit.
2. Add some code to `Swarm.TUI.Model.initUIState` which uses the GitHub API to request the hash of the most recent commit from the repo on github and check if it is the same as the has obtained locally.  If not, initialize the `uiError` widget so that it will pop up a dialog box warning you that you are running an out-of-date version.

**Comment by byorgey** [comment]
I just thought of a small wrinkle: it would be very annoying while developing and testing on some branch to have this always pop up because the latest commit on my branch does not match the latest commit on `main`.  So I guess it should also get the name of the current branch, and ask for the latest commit on the remote branch with the same name.

And there should probably also be a command-line flag `--no-update-check` or something to disable this behavior, since there's probably going to be some annoying case we didn't think of.

**Comment by byorgey** [comment]
For access to the github API, see https://hackage.haskell.org/package/github .

**Comment by byorgey** [comment]
See the above linked commit to see how to use `githash` to get the current branch and commit hash.

**Comment by xsebek** [comment]
> And there should probably also be a command-line flag --no-update-check or something to disable this behavior, since there's probably going to be some annoying case we didn't think of.

@byorgey how about adding a widget in the main menu instead that would share this wonderful news?

Something like:
```
   v<^vv<<@   ^^     vv    >^v^T    ^^^v<     <><      v   >
 T  ^<        >^  <  >>   v>   v<   >T   <v>  <<▒^  @><>    
    <@v^^>>   @v  >  <T  <v<T<^^>   v><v<     << <<T^ v<    
   >     >>   v@ @@> <<   ~v   <    >~  ^~    >>  @^  >v    
    >>^v^^^    < ~ T~v    v<   <~   >>T  <v   vv      ▒>    

               A new version v0.1.0 is available!

                             New game
                             Tutorial
                              About
                               Quit
```

**Comment by byorgey** [comment]
Ah, a widget on the main menu sounds nice.  Updating in parallel is easy: just fork off a thread to get the status from github and give it access to the same event channel where we currently write frame events, in `Swarm.App.appMain`.  Add a new constructor to the `AppEvent` type representing an update to the github status, then add a handler for it.

**Comment by xsebek** [comment]
In #652, I explored a bit how GitHub API could be used to get the latest release.

That to me sounds like the easiest approach and for players, it has the benefit of not bothering them every time something is committed upstream. :slightly_smiling_face:
