### ISSUE TITLE
Location watch command

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#687]
A neat optimisation would be to allow robots to let themselves be woken up when a selected location changes.

For example:
- in the game of life, the robots can wait until the neighbouring locations change
- in the Hanoi tower, robots only check the location where they are and a few known control locations

I propose adding a command `watch : int * int -> cmd ()`. If the specified location changes and the robot is
in the waiting robot queue, then it will be woken up like it reached the timeout. Otherwise, nothing happens.

---

Originally posted in the `#swarm` IRC channel:
```
<xsebek> I wonder if we could speedup swarm robots with something like "filewatch"
<xsebek> I am thinking about letting robots register to wait for changes to entity at some location
<xsebek> Not sure what the type would be 🤔
<xsebek> A simple solution would be to just wake up the robots on change
<xsebek> But to let robots register for multiple locations, just registering would not put them to waiting queue
<xsebek> So something like `repeat (watch (0,0); watch (3,1); wait 1024; doMyJob)`
<xsebek> Sorry I just feel bad for all the hanoi robots looking around, while I do nothing 😅
```

**Comment by byorgey** [comment]
I think this is a great idea, but I'm not sold on the proposed semantics for `watch` (or at least I think it needs to be clarified).  My initial reaction was to simplify things and just have `watch : int * int -> cmd ()` immediately sleep and wait until the specified cell changes.  But I guess you want to be able to watch multiple cells, and wake up if any one of them changes?

Once a robot executes `watch`, will it be watching that cell forever, i.e. until it is destroyed/salvaged?  Or do the watches get cleared when a robot becomes idle?  Or when it gets woken up?  Or is there a way to explicitly un-watch a cell?

**Comment by xsebek** [comment]
I would propose that watching a set of locations stops once the first location changes or the robot is woken up by timeout.

If the robot was waiting at that point it would be woken up and if it is doing something, nothing happens to it.

To keep it efficient we would need some data structure that has:
- an insertion of `RID` and `Location` and multiple insertions add more locations
- a query of `Location` that returns `Set RID`
- deletion of `RID` that removes the `RID` from all locations

---

But if there is no such thing, I can live with a `watch` that immediately sleeps - just add more robots and signalling `Location` to simulate OR. :grinning:

**Comment by byorgey** [comment]
OK, that makes sense.  In conjunction with this it might be nice to add a command `sleep` which is kind of like `wait infinity` --- it just goes to sleep indefinitely until woken by a `watch`ed location changing.  Otherwise I can imagine lots of situations where you have to write something ridiculous like `wait 1000000` and hope that it's long enough.

Sounds like a fun data structure challenge. :smile:  Actually I think it's not too bad: it can be done with a pair of maps, one `Map RID (Set Location)` and one `Map Location (Set RID)`:
- To insert an `(RID, Location)` pair, just do the obvious insertion in both maps.
- To query a `Location`, just do a lookup in the second map.
- To delete an `RID`, use the first map to find out which `Location`s it is associated to, then use them as keys into the second map to delete the given `RID` from their sets; finally, delete the `RID` from the first map.

**Comment by xsebek** [comment]
@byorgey sounds to me like a good motivation for adding infinity 😆 #656

**Comment by kostmo** [comment]
I think that being able to monitor arbitrary remote locations is effectively another way to enable "remote communication" a la #737.  That is, all of these things enable "coordination across a distance".

In terms of gameplay, I find some appeal in necessitating the building of some "sentinel robot" at the watch location which must then dash back to the base like [Pheidippides](https://en.wikipedia.org/wiki/Pheidippides) to notify it.

Or perhaps this issue is intended more of as a performance optimization for system robots?

**Comment by byorgey** [comment]
I think the ideas was just as an optimization for system robots.  You make a good argument why we shouldn't allow this for regular user robots.

**Comment by xsebek** [comment]
I don't see why regular robots should not be able (with proper device) watch at least their immediate surroundings.

Consider `meet` command. You could busy wait with it for a robot to show up, or you could watch the location in front of you.

The extra power is that you will be woken up exactly when the location changes and don’t need to mess with atomic.

But yes, it should foremost be a big performance optimisation in a few scenarios. 🙂

**Comment by kostmo** [comment]
Sounds like this issue is about support for [interrupts](https://en.wikipedia.org/wiki/Interrupt) as opposed to relying on [polling](https://en.wikipedia.org/wiki/Polling_(computer_science)).  Perhaps having interrupt support is more general than just location watching?

**Comment by xsebek** [comment]
That is a nice way to frame it.

I am not sure how you could further generalise this efficiently. The world with its locations is the analogue to computer with its signals.

If you would like more ways to wake up robots, perhaps a `wake` command would work? 🙂

**Comment by byorgey** [comment]
> I don't see why regular robots should not be able (with proper device) watch at least their immediate surroundings.
> 
> Consider `meet` command. You could busy wait with it for a robot to show up, or you could watch the location in front of you.

That is true, but the way this has been described so far (issue multiple `watch` commands and then later issue a `wait` command) I was not sure how to prevent robots from issuing a bunch of `watch` commands at various places and then driving far away and then finally doing `wait`.  Hmm, maybe it is not that hard --- perhaps non-system robots will only be woken by locations that are near them while doing `wait`?  In other words if you did `watch (0,0)`, then drive to `(100,0)`, then `watch (101,0)`, and then `wait 1024`, you would only actually be woken by something changing at `(101,0)` since `(0,0)` is too far away for you to notice anything.

**Comment by xsebek** [comment]
Now that I am thinking about it, this occurs to me as an ergonomic way to do it:
- each `watch (x,y)` is added to a list of robots watched locations
- at `wait` we clear the locations that the robot can not watch
- once the robot is woken up we clear all its watched locations

This should be correct and easy to implement. :thinking:

**Comment by kostmo** [comment]
How about we offer two variants of this command.

For system robots:
```
   spy : int * int -> cmd ()
```
Required capability: `god`

For player robots:
```
   watch : dir -> cmd ()
```
Required capability: `wakeself`
Device: `seismometer` (Description: Detects vibrations from nearby activity)

There are two benefits to using a direction instead of a location for the player variant:
* Reinforces that the watched location should be "nearby"
* Does not require a `"GPS receiver"` in order for the player to compute the watched location

Regarding the enforcement of watched locations, for player robots it should work exactly as [described above](https://github.com/swarm-game/swarm/issues/687#issuecomment-1377233608):

> - each `watch (x,y)` is added to a list of robots watched locations
> - at `wait` we clear the locations that the robot can not watch
> - once the robot is woken up we clear all its watched locations

But for system robots, the middle step (clearing distant locations) can be omitted.
