### ISSUE TITLE
In-game documentation of void

### ISSUE THREAD

**Issue by ussgarci** [swarm-game/swarm#753]
#665 added the `void` type to swarm and now it's time to brainstorm some ways for the players to discover it! 

An example would be to mention it in the description of an `ADT calculator`.

**Comment by byorgey** [comment]
I noticed that the `ADT calculator` description currently doesn't mention anything about `unit`, either (although `unit` is mentioned elsewhere, e.g. when talking about the `cmd` type).  Since the `ADT calculator` description already makes the connection between types and natural numbers, perhaps we could add something like "There are also types `unit` and `void` which correspond to the numbers 1 and 0, respectively."

**Comment by byorgey** [comment]
> We should add a way to show the description in a popup modal so that such long descriptions are easier to read. 

That already exists, just hit `Enter` on an inventory item.  But clearly we need to advertise it better!

**Comment by xsebek** [comment]
Oh, neat! I forgot about that. In my defence `[Ret] focus` is not what I would expect. :sweat_smile:
