### ISSUE TITLE
"Backstory" tutorial freezes and crashes upon incorrect input

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#756]
**Describe the bug**
In the first tutorial, the game pegs the CPU, consumes all memory, and is killed after typing: `say "whatever"` [enter] (instead of `say "Ready!"` [enter])

**To Reproduce**

   1. Start the "Backstory" tutorial, dismiss the Goal dialog.
   2. Type `say "z"` and hit Enter
   3. Observe CPU pegged, memory usage increase until the process is killed

**Expected behavior**
Memory/CPU should stay flat

**Screenshots**

![Screenshot from 2022-10-18 21-50-03](https://user-images.githubusercontent.com/261693/196600384-eb518d1b-6456-4289-bfc2-a1fd3044a414.png)

![Screenshot from 2022-10-18 21-40-26](https://user-images.githubusercontent.com/261693/196600017-f665d470-c93e-4b08-b74d-ebb9fb36a868.png)

**Additional context**
This is from the `main` branch (commit `b895668`), compiled and run via `stack run`.

**Comment by byorgey** [comment]
Yikes, thanks for the report @kostmo !  I can reproduce this.  

The problem seems to be that when the `listener` robot executes `say $ "Wrong message ...` then it `listen`s to itself and gets stuck in an infinite loop saying things like `"Wrong message: \"Wrong message: \\\"Wrong message: ...` with an exponentially growing number of backslashes. :laughing:   @xsebek, any ideas on the best way to fix this?  Do we need to change the way `listen` works?

**Comment by xsebek** [comment]
Ooops. :rofl: 

Easy fix: just `log` and do not `say`.

**Comment by byorgey** [comment]
> We should _definitely_ change `listen`, it is absurd that you would hear the same thing over and over again!
> Let's do that in a separate issue and discuss how exactly it should work.

Makes sense!  However, I don't think the robot is hearing the same thing over and over again.  The problem (IMO) is that it can hear itself.  So every time it executes `say` and then `listen` it hears what it just said, which causes it to `say` something again, ...
