### ISSUE TITLE
Inconsistent instructions about initial robot direction

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#757]
**Describe the bug**
In the "Build" tutorial, it says that "newly built robots always start out facing north". However, in the "Scan" tutorial, they start pointing East.

**To Reproduce**
Launch the "Build" tutorial, build one robot.  It will be facing East.

**Expected behavior**
Robot should be facing North.

**Screenshots**
![Screenshot from 2022-10-18 22-36-52](https://user-images.githubusercontent.com/261693/196606129-d51f4a75-6993-49f5-ae5a-eb4013ba6f53.png)

**Additional context**
This is from the `main` branch (commit `b895668`), compiled and run via `stack run`.

**Comment by byorgey** [comment]
@xsebek I have a different interpretation.  The fact that new robots will face the same direction as their parent robot is (IMO) a feature, not a bug.  It doesn't really make sense that a newly-built robot will *always* face north regardless of what direction the parent robot is facing (how would it know which way to face?).  When we say in the tutorial that "newly built robots always face north", what we meant (at least, what I thought we meant) is that we always arrange the `base` to be facing north, and hence constructed robots will be facing north.  The bug here is that the direction of the `base` in the `scan` tutorial is specified as `[1,0]` instead of `[0,1]`.  I propose:

1. We should fix the direction of `base` in the `scan` tutorial.
2. We should change line 1348 above to say `north` instead of `east`.  That line only applies if the parent robot does not have a direction but we might as well be consistent with the tutorial.
3. We should clarify the description in the `build` tutorial to say something like "newly built robots will always be facing the same direction as the robot that built them; in all the tutorials, the `base` robot is facing north."

**Comment by byorgey** [comment]
Yes, it's definitely my fault! :smile:
