### ISSUE TITLE
A way to "peek" under the robots

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#761]
**Is your feature request related to a problem? Please describe.**
At least from the tutorials, it's not clear whether it's possible to see what's "underneath" a robot without moving the robot.  It is desirable to see underneath the robot especially for plants like flowers or trees that change their state over time.

**Describe the solution you'd like**

Perhaps we should be able to hold down some keyboard combo to "peek underneath" (hide the robots) while the keys are depressed.  Or just have the key combo *toggle* robot visibility.  Or when the key combo is pressed, make the robots invisible for N seconds.  While the robot is hidden, can re-color the background of the tile that the robot is on.

**Describe alternatives you've considered**
* Provide the REPL command to see what is underneath the robot
* Continuously "blink" the robot when it is atop something

**Additional context**
This is from the `main` branch (commit `b895668`), compiled and run via `stack run`.

**Comment by byorgey** [comment]
Personally I don't like the idea of blinking robots, that seems like it would be visually really annoying, but I would be willing to try it to see how annoying it actually is.  However, I do like the idea of being able to toggle robot visibility with a key combo.

Note that it's not technically possible to implement something where the robots are hidden as long as you hold down a key combo and then reappear once you release it --- we don't get separate key pressed / key released events from the `vty` library, so we can't react to them separately.

**Comment by xsebek** [comment]
@byorgey if you hold a key, it will send repeatedly the same key to brick, so if we used a timeout for this it could work. :thinking: 

Also related:
- #523

**Comment by byorgey** [comment]
I'd be concerned that in a scenario where a user is holding down a key, we might not be able to keep up with the stream of repeated key events, causing the game to lag/freeze for a while even after the user releases the key.

**Comment by kostmo** [comment]
If there's a risk of falling behind in servicing the event queue, that's true we wouldn't want to encourage the user to hold down a key as part of normal play.

But is it already a concern today if the user holds down a key (for no functional reason)?  And should we design to be robust against such kind of (accidental or otherwise) input?

**Comment by byorgey** [comment]
Good question!  I don't know.  Whether we should guard against it maybe depends on how complex it would be to do so.  But you're right, we should also test it.

**Comment by xsebek** [comment]
> I'd be concerned that in a scenario where a user is holding down a key, we might not be able to keep up with the stream of repeated key events, causing the game to lag/freeze for a while even after the user releases the key.

@byorgey that would be very bad for a UI application. _But it does not happen._ Just hold down an arrow key in the world map.

It works fine. :wink: 

---

Seriously let's not do silly stuff like preventing users from holding down a key without first testing if it is even a problem. :smile: 

It is 100% normal for UI apps to handle events in a different thread and they do not normally<sup>[[1]](https://xkcd.com/1172/)</sup> explode.

This is stuff that brick API should support and if we encounter problems with it (unlikely because other more robust apps are using it too) we should report it. :slightly_smiling_face:

**Comment by xsebek** [comment]
Also, I think in this specific case it would cause us no trouble handling repeated visibility/blinking key - if we do not refresh the UI on each of them then it will only be an update of the UI state or no-op if it is already set.

Just set `blinkingViewedRobot` to `now+2s` and for the next two seconds, all handling of this key is a no-op. That should be much faster than the speed at which the keys are sent.

**Comment by byorgey** [comment]
> Seriously let's not do silly stuff like preventing users from holding down a key without first testing if it is even a problem.

> Also, I think in this specific case it would cause us no trouble handling repeated visibility/blinking key - if we do not refresh the UI on each of them then it will only be an update of the UI state or no-op if it is already set.

Yes, you're absolutely right, sorry for being silly. :smile:  I guess we are already set up to handle this well because of the fact that we do not redraw the UI with every keypress (which would be awful) but rather at a specific framerate independent of key events.

> Just set `blinkingViewedRobot` to `now+2s` and for the next two seconds, all handling of this key is a no-op. That should be much faster than the speed at which the keys are sent.

Makes sense. And I do like the idea of hitting a key to hide robots for 2s and then automatically show them again (rather than having to manually toggle it on/off).  I still don't think the robots should *blink* though.

**Comment by xsebek** [comment]
Here is how the blinking base would look:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/44544735/197333908-717f2463-c1c6-4176-96f9-1b5a203dce56.gif)
(I added a `blink :: attrName` that adds blink style to the robot attribute and changed the base display in the creative scenario.)

**Comment by xsebek** [comment]
> I still don't think the robots should blink though.

@byorgey since that sounds like something more people would like to style differently, why don't we allow customizing the behaviour? For start, we could add a `highlight-robot: <attrName>` to some configuration file. Even better would be to set it in `Settings` in the main Menu.

Then players could set the robot to invisible, highlighted, blinking, fire... depending on their preference.

**Comment by byorgey** [comment]
If we want to give players a way to style the focused/highlighted robot, sure.  We can split that out into another issue.  However, I don't think that solves the current issue.  IMO we need a way to make *all* the robots invisible for a short time, not just the currently viewed one.  Because you might have a lot of robots and it would be very tedious if you have to `view` each one first in order to see under it.

**Comment by xsebek** [comment]
@byorgey that sounds like a good plan of action to me. 👍 Also its probably closest to the original proposal.

I can look into this in the next few days. AFAIK it should just be about adding an “if” to the code that first checks robots and then the entity/terrain map.

But if anyone else wants to snatch this <kbd>Low hanging fruit</kbd> first, feel free! :wink:
