### ISSUE TITLE
Add descriptions to all (or most?) of the GitHub labels

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#789]
For example, what is the "Z-Meta" label supposed to be used for?

Currently, a few labels [do have descriptions](https://github.com/swarm-game/swarm/labels).

**Comment by xsebek** [comment]
@kostmo good point, I am procrastinating at the moment, so I will try to describe a few. :+1: 

---

The <kbd>Z-Meta</kbd> is for "things that are about things that are about Swarm."

Normally an issue is about a feature or bug of Swarm. A meta Issue is about those Issues.

In order to prevent Meta-Meta issues, we consider Issues about Meta Issues to be also just Meta Issues. :rofl:

**Comment by byorgey** [comment]
You managed to create a perfect instance of a `Z-Meta` issue by asking what `Z-Meta` means. :laughing:   Other `Z-Meta` issues have included things like discussing code formatting standards, keeping track of the alpha release.  Stuff that's not about Swarm directly but about the infrastructure surrounding it.

**Comment by byorgey** [comment]
The initial letters correspond to categories of labels, and are included so that the labels in each category show up consecutively when the labels are alphabetized.

* `C-`: how much work the issue will be to resolve.  I don't remember what C stands for.
* `G-`: which game elements are involved.
* `I-`: various ways an issue could be closed or "idle", i.e. something no one should be working on.
* `L-`: which language elements are involved.
* `S-`: the severity of the issue.
* `T-`: which component is involved.  I don't remember what T stands for.
* `Z-`: what kind of issue this is.

There are often fuzzy lines between various categories etc.  Feel free to invent new labels and/or reorganize a bit.

**Comment by byorgey** [comment]
@xsebek let me know when you get tired of procrastinating and I can take a pass at adding descriptions for more of the labels.

**Comment by byorgey** [comment]
All labels now have a description.  @kostmo , thanks for the nudge, and let us know if you have more questions!
