### ISSUE TITLE
Require a non-tree entity to craft a harvester

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#831]
If one wants to contrive a scenario where trees are "non-renewable" ingredients for crafting other items (e.g. only allow the player to `grab` rather than `harvest`), this is currently impossible because a tree is the only root entity needed to build a harvester.

I propose that the `harvester` recipe be modified to require a "metal gear" or some other non-tree-derived ingredient.  We would then modify all of the existing scenarios and make sure either that ingredient already exists in the inventory, or that it's easily obtainable.

**Alternative solution**

On second thought, to contrive such a non-renewable-resource scenario, one could just define a new tree-substitute entity (e.g. "bamboo") within the scenario, and provide alternative recipes to craft the existing tree-derived items from it (while purposely excluding `harvester`).

**Comment by byorgey** [comment]
It seems to me like there are better ways to create such non-renewable-resource scenarios, such as the one you mention with `bamboo`, or perhaps we could make a way for scenarios to *delete* certain entities from the entity map (i.e. declare them "off-limits"), just like currently scenarios can define their own new custom entities.  Then you could just delete `harvester` and the player would not be able to craft one, because it wouldn't exist.

I'm not really keen to make `harvester` more difficult to construct.  Part of the idea was that it's one of the first things you will probably want to make in a classic scenario game, so it needs to be easily constructible from very basic ingredients.
