### ISSUE TITLE
Prevent pushing to main branch unless by way of a Pull Request

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#832]
I just accidentally pushed [this commit](https://github.com/swarm-game/swarm/commit/146cd4b9a4a8aa1f3f8d00a5ba7d2ab480503439) to `main` from the command line.  I had meant to have discussion in a PR first.  It seems I cannot "force push" to roll back the commit.

On a positive note, it does compile and the scenario works:

    stack run -- --scenario Challenges/Ranching/gated-paddock --autoplay

**Comment by byorgey** [comment]
Haha, oops, I've done that before too.  I thought we did have it set up to only allow PRs, but I guess not.  Seems like a good thing to look into.

You can't force push to main but you could push a new commit that reverts the accidental one.  It doesn't actually quite work because it references your local filesystem :smile: .  The new scenario looks amazing though!

**Comment by byorgey** [comment]
OK, I think I've set it to only allow pushes to the `main` branch that come from merging a PR, disallowing direct pushes.

**Comment by kostmo** [comment]
Confirmed fixed, I cannot push directly to `main`.
