### ISSUE TITLE
In game command reference

### ISSUE THREAD

**Issue by Anrock** [swarm-game/swarm#84]
**Is your feature request related to a problem? Please describe.**
So far the only way to know about command is either tutorial file or checking part description on installed parts.
This isn't really convenient because:
1) Command descriptions are sort of scattered in flavour text
2) You have to have an entity with specific part to check it description (can't check move\turn commands if you don't have a robot for example)
3) Some commands are not described like "view" or "back" argument of turn.
4) Tutorial file sometimes goes out of sync with the game

**Describe the solution you'd like**
Centralized command reference which is available globally (can also be combined with syntax reference and maybe map legend for #49)
Command entry should consist of:
command (function) name, effects, type signature, required item/capability.

Preferably reference should be autogenerated to avoid synchronization issue like with tutorial file.

**Describe alternatives you've considered**
Leaving things as is.

**Additional context**
Check out [Colobot game](https://colobot.info/) which is pretty similar game about robot programming. It has a [SatCom](https://colobot.info/SatComOnline/master/cbot) system which is basically an ingame wiki with programming language syntax, API and list of entities.

**Comment by TristanCacqueray** [comment]
Thank you for writing down this issue and providing the *Colobot* example, that's super valuable.

I actually started to put together a Help panel in #83 with a simple list of command. Though I'm not sure this should be the place for such centralized command reference since all the command are not available by default.

**Comment by byorgey** [comment]
Thanks for making this issue.  I think some kind of in-game language reference like this will be super valuable, and perhaps it could be incorporated into the help panel.

One thing we should consider is how comprehensive the in-game language reference should be.  Right now (though I could be convinced otherwise) I don't think it should cover absolutely everything.  You want to leave some fun things for players to discover for themselves, and also don't want it to be overwhelming for new players.  However, I am totally OK with having a completely comprehensive language reference externally to the game, on a wiki or `readthedocs.io` or something like that.

**Comment by Anrock** [comment]
> Though I'm not sure this should be the place for such centralized command reference since all the command are not available by default.

I was thinking it should be unlockable. So command entries should be added only after you have obtained a corresponding part or a recipe for crafting it is known.

**Comment by byorgey** [comment]
Thinking more about this.  Right now `generateModal` in `TUI.View` creates the (static) help window.  I guess we can just pass along the `GameState` to the `generateModal` function so that it can figure out what help to display based on discovered devices.

I think the formatting of the help needs to be updated as well.  It should definitely show the *types* of the commands, which it currently does not.  Putting the lists of commands and keys in tables with borders around all the cells also wastes a lot of space, I think we can probably lay things out better than that.  Also, maybe the help window will need to be scrollable once you discover a bunch of commands.

**Comment by xsebek** [comment]
There is also no in-game reference for `back`/`down`/`forward`.

`threads` only gives an example:
```bash
move; turn left; move; turn north
```

I would like to have a types overview in-game as well, could be useful with future types. :slightly_smiling_face:

**Comment by byorgey** [comment]
This was closed by #458 .
