### ISSUE TITLE
Support eglot for Emacs editing

### ISSUE THREAD

**Issue by librarianmage** [swarm-game/swarm#860]
**Is your feature request related to a problem? Please describe.**
The current `swarm-mode` package relies on the `emacs-lsp` package in order to support LSP integration, which is not the LSP server package I use. I use [eglot](https://elpa.gnu.org/packages/eglot.html) instead.

**Describe the solution you'd like**
I would like the package to also support eglot as well.

**Additional context**
Eglot has been [merged into emacs itself](https://www.reddit.com/r/emacs/comments/y94nxp/eglot_is_merged_into_emacs_git_master/).

**Comment by xsebek** [comment]
Hi @librarianmage, thanks for bringing up Eglot. I admit I do not use Emacs, that would be @byorgey. :slightly_smiling_face: 

Based on the Eglot documentation it seems we only need to change the `with-eval-after-load` section of `swarm-mode.el`:
- https://joaotavora.github.io/eglot/#Setting-Up-LSP-Servers

It would be nice if the same script could detect which of the two LSP packages are available and import&use the right one.

But we could also just copy and paste the syntax highlighting to another file, it does not change much and we test that it is up to date in the CI. :man_shrugging:

**Comment by byorgey** [comment]
Hi @librarianmage , thanks for mentioning this! I actually had not heard of `eglot` before.  We would be happy to support it, but realistically, since none of the current developers use it, it would require someone to send a PR and promise to try to support it in the future if something breaks.

In the meantime, my understanding is that you can have both `eglot` and `lsp-emacs` installed, and configure emacs to load the right one depending on the mode.

**Comment by byorgey** [comment]
Closing this as won'tfix for now.  But as mentioned above we would be happy to merge a PR adding support for eglot.
