### ISSUE TITLE
Way for a robot to lose movement ability

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#883]
**Is your feature request related to a problem? Please describe.**

Currently, once an inventory item is `install`ed, onto a robot, that robot will have the provided abilities forever.  This limits the possibilities for contriving interesting scenarios with limited resources.

In particular, having a robot lose its ability to move would be an interesting play mechanic.

This could be related to all of the following:
* taking damage (#89)
* exhausting fuel (#550), or
* getting stuck in a swamp (#205)

Or, a robot may voluntarily give up its "treads" to cannibalize them for parts.

**Describe the solution you'd like**
Provide a command named `uninstall` or `unequip` that restores the installed item back into the inventory.

    unequip : text -> cmd unit

**Describe alternatives you've considered**
Provide a command called `disable` that destroys an installed device (does not restore it back to inventory) and requires the (e.g.) `aggressor` capability.

    disable : robot -> text -> cmd unit

**Comment by byorgey** [comment]
I like the idea of an `uninstall`/`unequip` command.  I especially like the idea of having *e.g.* just one or two `treads` and having to share them between multiple robots.

Though you could definitely get yourself stuck using it, *e.g.* imagine that you `uninstall` your `3D printer` and then `give` it to another robot.  Now there's no way to get it back because *e.g.* you can't `build` another robot to go `salvage` it for you.  But maybe that is OK!

I was going to say it should be named `uninstall` in parallel with `install`.  But then I realized, perhaps "install" is something you do to another robot, whereas "equip" is something you do to yourself?  I don't know, I think players would still be confused by having `install` but `unequip`.  I don't think there's any need to also provide an `equip : text -> cmd unit` command since you can always `install self`.

**Comment by kostmo** [comment]
> Though you could definitely get yourself stuck using it

I think that "getting stuck" should be normalized as a *possibility* in the game, especially since we have a dedicated button to restart the scenario.  Unlike some other games where it might be quite frustrating to "lose progress" involving feats of precise manual timing, our progress is stored in code and can be recalled from the REPL history.

> I was going to say it should be named `uninstall` in parallel with `install`

I think it makes sense to have `equip`/`unequip` have a type signature of `text -> cmd unit` whereas `install`/`uninstall` have `robot -> text -> cmd unit`.

Though TBH I've only ever used `install` on `self`.  And the "proximity" requirements of performing `install` on another robot aren't clearly documented (see #884).

**Comment by byorgey** [comment]
Yeah, now that we have `require`, there's less need to use `install` on other robots.  Maybe we should just get rid of `install` and have `equip`/`unequip`?

**Comment by byorgey** [comment]
> I think that "getting stuck" should be normalized as a _possibility_ in the game, especially since we have a dedicated button to restart the scenario. Unlike some other games where it might be quite frustrating to "lose progress" involving feats of precise manual timing, our progress is stored in code and can be recalled from the REPL history.

Makes sense!
